### ISSUE TITLE
Question: Input field

### ISSUE THREAD

**Issue by Irontale** [terminal42/contao-tablelookupwizard#11]
Hey there,
I wondered if it is possible to add a textfield to each list entry.

For example:
```
____________________________________________
| Checkbox | Field 1 | Field 2 | Textfield |
| Checkbox | Field 1 | Field 2 | Textfield |
| Checkbox | Field 1 | Field 2 | Textfield |
```

**Comment by qzminski** [comment]
I think it's not a purpose of this extension. However you could have to create your own widget which extends tablelookupwizard to use it as a base.

**Comment by Irontale** [comment]
Ok, I see. Can you guide me into a direction on how to do this? :-)

**Comment by qzminski** [comment]
If you are not familiar with PHP I suggest that you hire someone to do it for you as this job requires some knowledge about OOP and Contao itself.

**Comment by Irontale** [comment]
I am very familiar with PHP and do have knowledge about OOP. I also made some Rocksolid Custom Elements and figured out most of the extension hierarchy. But I am using [isotope_quickproducts](https://github.com/RhymeDigital/isotope_quickproducts) (which already uses tablelookupwizard), to implement a list of products into a page. I want to add a predefined quantity to each product, which vary on each page so I have to add the quantity value to each added list entry. Or is there some different approach available?

**Comment by qzminski** [comment]
In such case your initial concept seems to be correct. I would suggest to register your new backend widget in ```$GLOBALS['BE_FFL']``` array. The widget class should extends the tablelookupwizard and would override methods such as ```getBody()``` where you have to change to a new template based on the ```be_widget_tablelookupwizard_content``` template which will be capable of generating an extra text field in the last column.

Once you are done with GUI you also have to pay attention to the ```validator()``` method because the value you are going to save into the database will still be a serialized array but in a slightly different format:

```
Array( [product_id] => [quantity] )
```

Also make sure that the IDs are now fetched differently (e.g. still from the value but through ```array_keys```) and pass the product quantities to the template as well.

https://github.com/terminal42/contao-tablelookupwizard/blob/master/TableLookupWizard.php#L196
